version: "3.4"

services:
  app:
    image: dkr-30-voting_app
    build: .
    environment:
      DB_PASSWORD: forge
      DB_HOST: rbm30_db
      REDIS_HOST: rbm30_redis
    volumes:
      - app:/var/www/html
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: app.logs


  nginx:
    image: dkr-30-voting_nginx
    depends_on:
      - app
    build:
      context: ./nginx/
    volumes:
      - app:/var/www/html
    networks:
      - traefik-public
      - default
    deploy:
#      placement:
#        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
#          - node.labels.role == manager
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.rbm30_nginx.rule=Host(`app.147.182.184.106.nip.io`, `app.67.205.144.9.nip.io`, `app.147.182.186.151.nip.io`)
        - traefik.http.routers.rbm30_nginx.entrypoints=http
        - traefik.http.routers.rbm30_nginx.service=app
        - traefik.http.services.app.loadbalancer.server.port=80

        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true


        - traefik.http.routers.rbm30_nginx_https.rule=Host(`app.147.182.184.106.nip.io`, `app.67.205.144.9.nip.io`, `app.147.182.186.151.nip.io`)
        - traefik.http.routers.rbm30_nginx_https.entrypoints=https
        - traefik.http.routers.rbm30_nginx_https.service=app_https
        - traefik.http.services.app_https.loadbalancer.server.port=80
        - traefik.http.routers.rbm30_nginx_https.tls.certresolver=le # <== Defining certsresolvers for https
        - traefik.docker.network=traefik-public
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: nginx.access


  db:
    image: dkr-30-voting_db
    build:
      context: ./database/
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: forge
      MYSQL_PASSWORD: forge
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - vol1:/var/lib/mysql
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: mysql.logs


  redis:
    image: dkr-30-voting_redis
    build:
      context: ./config/
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: redis.logs


volumes:
  app: {}
  vol1:
    driver: glusterfs:latest
    name: "gfs"


networks:
  traefik-public:
    external: true
  default:
    external: false