version: "3.4"

services:

  elasticsearch:
    image: dkr-30-voting_elasticsearch
    build:
      context: ./elasticsearch/
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - vol2:/usr/share/elasticsearch
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public

  kibana:
    depends_on:
      - elasticsearch
    image: dkr-30-voting_kibana
    build:
      context: ./kibana/
    ports:
      - 5601:5601
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.protocol=http
        - traefik.http.routers.efk_kibana.entrypoints=http
        - traefik.http.services.kibana.loadbalancer.server.port=5601
        - traefik.http.routers.efk_kibana.rule=Host(`kibana.143.198.123.38.nip.io`)
        - traefik.docker.network=traefik-public

        - traefik.http.routers.efk_kibana-https.rule=Host(`kibana.143.198.123.38.nip.io`)
        - traefik.http.routers.efk_kibana-https.entrypoints=https
        - traefik.http.routers.efk_kibana-https.tls=true
    # Using the environment variables USERNAME and HASHED_PASSWORD
        - traefik.http.middlewares.kibana-auth.basicauth.users=${USERNAME_KIBANA?Variable not set}:${HASHED_PASSWORD_KIBANA?Variable not set}
        - traefik.http.routers.efk_kibana.middlewares=kibana-auth
        - traefik.http.routers.efk_kibana-https.middlewares=kibana-auth

#        - traefik.http.middlewares.kibana-auth.redirectscheme.scheme=https
#        - traefik.http.middlewares.kibana-auth.redirectscheme.permanent=true


    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public

  fluentd:
    depends_on:
      - elasticsearch
    image: dkr-30-voting_fluentd
    build:
      context: ./fluentd/
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public

volumes:
  vol2:
    driver: glusterfs:latest
    name: "elastic"

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true